export interface CompanyCategoryDef {
  id: string;
  name: string;
  iconName:
    | "Flame"
    | "TrendingUp"
    | "Briefcase"
    | "Crown"
    | "Landmark"
    | "Cloud"
    | "Cpu"
    | "ShoppingBag"
    | "Gamepad2"
    | "Activity";
  slugs: string[];
}

export const COMPANY_CATEGORIES: CompanyCategoryDef[] = [
  {
    id: "faang",
    name: "FAANG & Big Tech",
    iconName: "Flame",
    slugs: [
      "google",
      "meta",
      "amazon",
      "apple",
      "netflix",
      "microsoft",
      "bytedance",
      "adobe",
      "linkedin",
      "salesforce",
      "nvidia",
    ],
  },
  {
    id: "hft",
    name: "HFT & Quant Trading",
    iconName: "TrendingUp",
    slugs: [
      "citadel",
      "jane-street",
      "two-sigma",
      "hudson-river-trading",
      "jump-trading",
      "optiver",
      "drw",
      "sig",
      "tower-research-capital",
      "akuna-capital",
      "squarepoint-capital",
      "worldquant",
      "five-rings",
      "imcap",
    ],
  },
  {
    id: "banking",
    name: "Banking & Investment",
    iconName: "Landmark",
    slugs: [
      "goldman-sachs",
      "morgan-stanley",
      "jpmorgan",
      "citigroup",
      "citi",
      "capital-one",
      "barclays",
      "credit-suisse",
      "hsbc",
      "bank-of-america",
      "wells-fargo",
      "ubs",
      "deutsche-bank",
      "fidelity",
      "blackrock",
      "bloomberg",
      "american-express",
      "visa",
      "mastercard",
      "paypal",
    ],
  },
  {
    id: "product",
    name: "Fintech & Product Unicorns",
    iconName: "Crown",
    slugs: [
      "uber",
      "airbnb",
      "stripe",
      "coinbase",
      "doordash",
      "door-dash",
      "robinhood",
      "databricks",
      "snowflake",
      "atlassian",
      "palantir-technologies",
      "palantir",
      "snap",
      "pinterest",
      "tiktok",
      "reddit",
      "lyft",
      "twilio",
      "instacart",
      "zoom",
      "spotify",
      "slack",
      "dropbox",
      "quora",
      "square",
      "block",
    ],
  },
  {
    id: "cloud",
    name: "Enterprise & Cloud Software",
    iconName: "Cloud",
    slugs: [
      "oracle",
      "sap",
      "vmware",
      "workday",
      "servicenow",
      "cisco",
      "ibm",
      "splunk",
      "mongodb",
      "intuit",
      "autodesk",
      "asana",
      "hubspot",
      "box",
      "zendesk",
      "datadog",
      "confluent",
      "elastic",
      "cloudflare",
      "hashicorp",
      "fastly",
    ],
  },
  {
    id: "hardware",
    name: "Hardware & Semiconductors",
    iconName: "Cpu",
    slugs: [
      "intel",
      "amd",
      "qualcomm",
      "broadcom",
      "tsmc",
      "samsung",
      "texas-instruments",
      "micron",
      "arm",
      "applied-materials",
      "asml",
      "western-digital",
      "seagate",
      "marvell",
      "mediatek",
      "huawei",
    ],
  },
  {
    id: "ecommerce",
    name: "E-Commerce & Retail Tech",
    iconName: "ShoppingBag",
    slugs: [
      "flipkart",
      "meesho",
      "walmart",
      "ebay",
      "wayfair",
      "target",
      "best-buy",
      "carvana",
      "coupang",
      "shopee",
      "mercari",
      "zalando",
      "etsy",
      "chewy",
      "wish",
      "rakuten",
    ],
  },
  {
    id: "gaming",
    name: "Gaming & Interactive",
    iconName: "Gamepad2",
    slugs: [
      "electronic-arts",
      "ea",
      "roblox",
      "epic-games",
      "unity",
      "riot-games",
      "blizzard",
      "twitch",
      "sony",
      "nintendo",
      "ubisoft",
      "take-two",
      "zynga",
    ],
  },
  {
    id: "health",
    name: "Healthcare & Biotech",
    iconName: "Activity",
    slugs: [
      "johnson-johnson",
      "pfizer",
      "optum",
      "unitedhealth",
      "epic-systems",
      "athenahealth",
      "veeva",
      "cerner",
      "dexcom",
      "oscar-health",
    ],
  },
  {
    id: "service",
    name: "Service & IT Consulting",
    iconName: "Briefcase",
    slugs: [
      "tcs",
      "infosys",
      "wipro",
      "accenture",
      "cognizant",
      "capgemini",
      "hcl",
      "tech-mahindra",
      "epam-systems",
      "deloitte",
      "pwc",
      "ey",
      "kpmg",
      "mindsytree",
      "ltimindtree",
    ],
  },
];
